name: Leak Check

on:
  push:
    branches:
      - master

jobs:
  check-leaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run GitLeaks
      uses: zricethezav/gitleaks-action@master
